### PR TITLE
Uses readStreamToString from apify shared. Fixes proxy-agent.

### LINKED ISSUE #26: Use readStreamToString from apify-shared package
The function was moved to:
https://github.com/apifytech/apify-shared-js/blob/master/src/streams_utilities.js#L28

connected with
https://github.com/apifytech/apify-js/issues/471

### LINKED ISSUE #27: `https-proxy-agent ` update due to security vulnerability.
https://github.com/TooTallNate/node-proxy-agent

### PR DESCRIPTION
**Pull request by petrpatek**
Fixes #26 and  Fixes #27

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -79,31 +78,29 @@ const createCaseSensitiveHook = require('./create_case_sensitive_hook');
...
+        followRedirect = REQUEST_DEFAULT_OPTIONS.followRedirect,
+        maxRedirects = REQUEST_DEFAULT_OPTIONS.maxRedirects,
+        throwOnHttpErrors = REQUEST_DEFAULT_OPTIONS.throwHttpErrors,
+        abortFunction = REQUEST_DEFAULT_OPTIONS.abortFunction,
+        timeoutSecs = REQUEST_DEFAULT_OPTIONS.timeoutSecs,
+        ignoreSslErrors = REQUEST_DEFAULT_OPTIONS.ignoreSslErrors,
+        decodeBody = REQUEST_DEFAULT_OPTIONS.decodeBody,
+        json = REQUEST_DEFAULT_OPTIONS.json,
+        stream = REQUEST_DEFAULT_OPTIONS.stream,
+        useBrotli = REQUEST_DEFAULT_OPTIONS.useBrotli,
```
Comment (mnmkng) [inline src/index.js]: This is unnecessarily complicated. Just delete the constants file and move the default values directly here. Unless you need them elsewhere?

Comment (petrpatek) [reply src/index.js]: Yes, I need them in the tests...

Comment (mnmkng) [reply src/index.js]: It kinda kills the point of having the defaults readable where they're used though :D
